let cityData = '[{"name":"北京","tipData":[{"name":"设备总数","value":152213},{"name":"企业总数","value":46}],"value":10},{"name":"江苏","tipData":[{"name":"设备总数","value":143974},{"name":"企业总数","value":484}],"value":10},{"name":"广东","tipData":[{"name":"设备总数","value":132377},{"name":"企业总数","value":38}],"value":10},{"name":"山东","tipData":[{"name":"设备总数","value":99817},{"name":"企业总数","value":3}],"value":10},{"name":"河南","tipData":[{"name":"设备总数","value":38975},{"name":"企业总数","value":1}],"value":10},{"name":"天津","tipData":[{"name":"设备总数","value":33150},{"name":"企业总数","value":14}],"value":10},{"name":"上海","tipData":[{"name":"设备总数","value":28495},{"name":"企业总数","value":5}],"value":10},{"name":"浙江","tipData":[{"name":"设备总数","value":24441},{"name":"企业总数","value":7}],"value":10},{"name":"山西","tipData":[{"name":"设备总数","value":23695},{"name":"企业总数","value":0}],"value":10},{"name":"河北","tipData":[{"name":"设备总数","value":18115},{"name":"企业总数","value":12}],"value":10},{"name":"贵州","tipData":[{"name":"设备总数","value":14602},{"name":"企业总数","value":16}],"value":10},{"name":"辽宁","tipData":[{"name":"设备总数","value":13932},{"name":"企业总数","value":15}],"value":10},{"name":"重庆","tipData":[{"name":"设备总数","value":13713},{"name":"企业总数","value":10}],"value":10},{"name":"福建","tipData":[{"name":"设备总数","value":9659},{"name":"企业总数","value":3}],"value":10},{"name":"江西","tipData":[{"name":"设备总数","value":9055},{"name":"企业总数","value":6}],"value":10},{"name":"安徽","tipData":[{"name":"设备总数","value":6714},{"name":"企业总数","value":0}],"value":10},{"name":"四川","tipData":[{"name":"设备总数","value":5672},{"name":"企业总数","value":84}],"value":10},{"name":"湖北","tipData":[{"name":"设备总数","value":5153},{"name":"企业总数","value":9}],"value":10},{"name":"甘肃","tipData":[{"name":"设备总数","value":3356},{"name":"企业总数","value":3}],"value":10},{"name":"宁夏回族","tipData":[{"name":"设备总数","value":3205}],"value":10},{"name":"广西壮族","tipData":[{"name":"设备总数","value":2444},{"name":"企业总数","value":2}],"value":10},{"name":"湖南","tipData":[{"name":"设备总数","value":1945},{"name":"企业总数","value":3}],"value":10},{"name":"内蒙古","tipData":[{"name":"设备总数","value":1110},{"name":"企业总数","value":9}],"value":10},{"name":"新疆","tipData":[{"name":"设备总数","value":1041},{"name":"企业总数","value":0}],"value":10},{"name":"吉林","tipData":[{"name":"设备总数","value":1027},{"name":"企业总数","value":2}],"value":10},{"name":"陕西","tipData":[{"name":"设备总数","value":800},{"name":"企业总数","value":5}],"value":10},{"name":"黑龙江","tipData":[{"name":"设备总数","value":737},{"name":"企业总数","value":2}],"value":10},{"name":"云南","tipData":[{"name":"设备总数","value":168},{"name":"企业总数","value":3}],"value":10},{"name":"西藏","tipData":[{"name":"设备总数","value":2},{"name":"企业总数","value":1}],"value":10},{"name":null,"tipData":[{"name":"设备总数","value":1}],"value":10},{"name":"东城区","value":10,"tipData":[{"name":"设备总数","value":152284},{"name":"企业总数","value":1}]},{"name":"济南市","value":10,"tipData":[{"name":"设备总数","value":77111},{"name":"企业总数","value":1}]},{"name":"珠海市","value":10,"tipData":[{"name":"设备总数","value":66259},{"name":"企业总数","value":1}]},{"name":"常州市","value":10,"tipData":[{"name":"设备总数","value":39205},{"name":"企业总数","value":1}]},{"name":"河东区","value":10,"tipData":[{"name":"设备总数","value":33150},{"name":"企业总数","value":1}]},{"name":"苏州市","value":10,"tipData":[{"name":"设备总数","value":29397},{"name":"企业总数","value":1}]},{"name":"浦东新区","value":10,"tipData":[{"name":"设备总数","value":28401},{"name":"企业总数","value":1}]},{"name":"广州市","value":10,"tipData":[{"name":"设备总数","value":24567},{"name":"企业总数","value":1}]},{"name":"扬州市","value":10,"tipData":[{"name":"设备总数","value":23943},{"name":"企业总数","value":1}]},{"name":"南京市","value":10,"tipData":[{"name":"设备总数","value":15280},{"name":"企业总数","value":1}]},{"name":"北碚区","value":10,"tipData":[{"name":"设备总数","value":13691},{"name":"企业总数","value":1}]},{"name":"贵阳市","value":10,"tipData":[{"name":"设备总数","value":13360},{"name":"企业总数","value":1}]},{"name":"秦皇岛市","value":10,"tipData":[{"name":"设备总数","value":12767},{"name":"企业总数","value":1}]},{"name":"无锡市","value":10,"tipData":[{"name":"设备总数","value":12134},{"name":"企业总数","value":1}]},{"name":"滨州市","value":10,"tipData":[{"name":"设备总数","value":11412},{"name":"企业总数","value":1}]},{"name":"大同市","value":10,"tipData":[{"name":"设备总数","value":10734},{"name":"企业总数","value":1}]},{"name":"深圳市","value":10,"tipData":[{"name":"设备总数","value":10564},{"name":"企业总数","value":1}]},{"name":"杭州市","value":10,"tipData":[{"name":"设备总数","value":10163},{"name":"企业总数","value":1}]},{"name":"沈阳市","value":10,"tipData":[{"name":"设备总数","value":8511},{"name":"企业总数","value":1}]},{"name":"鹰潭市","value":10,"tipData":[{"name":"设备总数","value":7906},{"name":"企业总数","value":1}]},{"name":"朔州市","value":10,"tipData":[{"name":"设备总数","value":7733},{"name":"企业总数","value":1}]},{"name":"镇江市","value":10,"tipData":[{"name":"设备总数","value":7435},{"name":"企业总数","value":1}]},{"name":"郑州市","value":10,"tipData":[{"name":"设备总数","value":6519},{"name":"企业总数","value":1}]},{"name":"洛阳市","value":10,"tipData":[{"name":"设备总数","value":5452},{"name":"企业总数","value":1}]},{"name":"淮安市","value":10,"tipData":[{"name":"设备总数","value":5451},{"name":"企业总数","value":1}]},{"name":"台州市","value":10,"tipData":[{"name":"设备总数","value":5301},{"name":"企业总数","value":1}]},{"name":"温州市","value":10,"tipData":[{"name":"设备总数","value":5083},{"name":"企业总数","value":1}]},{"name":"大连市","value":10,"tipData":[{"name":"设备总数","value":5062},{"name":"企业总数","value":1}]},{"name":"平顶山市","value":10,"tipData":[{"name":"设备总数","value":4995},{"name":"企业总数","value":1}]},{"name":"盐城市","value":10,"tipData":[{"name":"设备总数","value":4782},{"name":"企业总数","value":1}]},{"name":"新乡市","value":10,"tipData":[{"name":"设备总数","value":4677},{"name":"企业总数","value":1}]},{"name":"宣城市","value":10,"tipData":[{"name":"设备总数","value":4003},{"name":"企业总数","value":1}]},{"name":"成都市","value":10,"tipData":[{"name":"设备总数","value":3623},{"name":"企业总数","value":1}]},{"name":"泰州市","value":10,"tipData":[{"name":"设备总数","value":3526},{"name":"企业总数","value":1}]},{"name":"宿迁市","value":10,"tipData":[{"name":"设备总数","value":3498},{"name":"企业总数","value":1}]},{"name":"清远市","value":10,"tipData":[{"name":"设备总数","value":3427},{"name":"企业总数","value":1}]},{"name":"兰州市","value":10,"tipData":[{"name":"设备总数","value":3349},{"name":"企业总数","value":1}]},{"name":"南通市","value":10,"tipData":[{"name":"设备总数","value":3296},{"name":"企业总数","value":1}]},{"name":"泰安市","value":10,"tipData":[{"name":"设备总数","value":3284},{"name":"企业总数","value":1}]},{"name":"广东省","value":10,"tipData":[{"name":"设备总数","value":3177},{"name":"企业总数","value":1}]},{"name":"十堰市","value":10,"tipData":[{"name":"设备总数","value":3047},{"name":"企业总数","value":1}]},{"name":"青岛市","value":10,"tipData":[{"name":"设备总数","value":2916},{"name":"企业总数","value":1}]},{"name":"银川市","value":10,"tipData":[{"name":"设备总数","value":2705},{"name":"企业总数","value":1}]},{"name":"佛山市","value":10,"tipData":[{"name":"设备总数","value":2619},{"name":"企业总数","value":1}]},{"name":"河源市","value":10,"tipData":[{"name":"设备总数","value":2594},{"name":"企业总数","value":1}]},{"name":"焦作市","value":10,"tipData":[{"name":"设备总数","value":2493},{"name":"企业总数","value":1}]},{"name":"茂名市","value":10,"tipData":[{"name":"设备总数","value":2400},{"name":"企业总数","value":1}]},{"name":"商丘市","value":10,"tipData":[{"name":"设备总数","value":2252},{"name":"企业总数","value":1}]},{"name":"驻马店市","value":10,"tipData":[{"name":"设备总数","value":2249},{"name":"企业总数","value":1}]},{"name":"鹤壁市","value":10,"tipData":[{"name":"设备总数","value":2016},{"name":"企业总数","value":1}]},{"name":"连云港市","value":10,"tipData":[{"name":"设备总数","value":2000},{"name":"企业总数","value":1}]},{"name":"太原市","value":10,"tipData":[{"name":"设备总数","value":1960},{"name":"企业总数","value":1}]},{"name":"廊坊市","value":10,"tipData":[{"name":"设备总数","value":1930},{"name":"企业总数","value":1}]},{"name":"临沂市","value":10,"tipData":[{"name":"设备总数","value":1921},{"name":"企业总数","value":1}]},{"name":"安阳市","value":10,"tipData":[{"name":"设备总数","value":1594},{"name":"企业总数","value":1}]},{"name":"武汉市","value":10,"tipData":[{"name":"设备总数","value":1578},{"name":"企业总数","value":1}]},{"name":"临汾市","value":10,"tipData":[{"name":"设备总数","value":1537},{"name":"企业总数","value":1}]},{"name":"惠州市","value":10,"tipData":[{"name":"设备总数","value":1534},{"name":"企业总数","value":1}]},{"name":"潮州市","value":10,"tipData":[{"name":"设备总数","value":1524},{"name":"企业总数","value":1}]},{"name":"开封市","value":10,"tipData":[{"name":"设备总数","value":1479},{"name":"企业总数","value":1}]},{"name":"嘉兴市","value":10,"tipData":[{"name":"设备总数","value":1465},{"name":"企业总数","value":1}]},{"name":"邯郸市","value":10,"tipData":[{"name":"设备总数","value":1442},{"name":"企业总数","value":1}]},{"name":"云浮市","value":10,"tipData":[{"name":"设备总数","value":1422},{"name":"企业总数","value":1}]},{"name":"汕尾市","value":10,"tipData":[{"name":"设备总数","value":1347},{"name":"企业总数","value":1}]},{"name":"梅州市","value":10,"tipData":[{"name":"设备总数","value":1328},{"name":"企业总数","value":1}]},{"name":"汕头市","value":10,"tipData":[{"name":"设备总数","value":1305},{"name":"企业总数","value":1}]},{"name":"肇庆市","value":10,"tipData":[{"name":"设备总数","value":1300},{"name":"企业总数","value":1}]},{"name":"揭阳市","value":10,"tipData":[{"name":"设备总数","value":1279},{"name":"企业总数","value":1}]},{"name":"运城市","value":10,"tipData":[{"name":"设备总数","value":1256},{"name":"企业总数","value":1}]},{"name":"柳州市","value":10,"tipData":[{"name":"设备总数","value":1250},{"name":"企业总数","value":1}]},{"name":"韶关市","value":10,"tipData":[{"name":"设备总数","value":1234},{"name":"企业总数","value":1}]},{"name":"烟台市","value":10,"tipData":[{"name":"设备总数","value":1213},{"name":"企业总数","value":1}]},{"name":"南阳市","value":10,"tipData":[{"name":"设备总数","value":1199},{"name":"企业总数","value":1}]},{"name":"湛江市","value":10,"tipData":[{"name":"设备总数","value":1194},{"name":"企业总数","value":1}]},{"name":"江门市","value":10,"tipData":[{"name":"设备总数","value":1183},{"name":"企业总数","value":1}]},{"name":"三门峡市","value":10,"tipData":[{"name":"设备总数","value":1151},{"name":"企业总数","value":1}]},{"name":"绍兴市","value":10,"tipData":[{"name":"设备总数","value":1141},{"name":"企业总数","value":1}]},{"name":"濮阳市","value":10,"tipData":[{"name":"设备总数","value":1000},{"name":"企业总数","value":1}]},{"name":"信阳市","value":10,"tipData":[{"name":"设备总数","value":998},{"name":"企业总数","value":1}]},{"name":"徐州市","value":10,"tipData":[{"name":"设备总数","value":980},{"name":"企业总数","value":1}]},{"name":"东莞市","value":10,"tipData":[{"name":"设备总数","value":941},{"name":"企业总数","value":1}]},{"name":"三明市","value":10,"tipData":[{"name":"设备总数","value":882},{"name":"企业总数","value":1}]},{"name":"吉林市","value":10,"tipData":[{"name":"设备总数","value":863},{"name":"企业总数","value":1}]},{"name":"合肥市","value":10,"tipData":[{"name":"设备总数","value":849},{"name":"企业总数","value":1}]},{"name":"厦门市","value":10,"tipData":[{"name":"设备总数","value":762},{"name":"企业总数","value":1}]},{"name":"长沙市","value":10,"tipData":[{"name":"设备总数","value":758},{"name":"企业总数","value":1}]},{"name":"沧州市","value":10,"tipData":[{"name":"设备总数","value":718},{"name":"企业总数","value":1}]},{"name":"乌鲁木齐市","value":10,"tipData":[{"name":"设备总数","value":703},{"name":"企业总数","value":1}]},{"name":"周口市","value":10,"tipData":[{"name":"设备总数","value":701},{"name":"企业总数","value":1}]},{"name":"阳江市","value":10,"tipData":[{"name":"设备总数","value":651},{"name":"企业总数","value":1}]},{"name":"德阳市","value":10,"tipData":[{"name":"设备总数","value":614},{"name":"企业总数","value":1}]},{"name":"眉山市","value":10,"tipData":[{"name":"设备总数","value":608},{"name":"企业总数","value":1}]},{"name":"湘潭市","value":10,"tipData":[{"name":"设备总数","value":537},{"name":"企业总数","value":1}]},{"name":"益阳市","value":10,"tipData":[{"name":"设备总数","value":531},{"name":"企业总数","value":1}]},{"name":"中山市","value":10,"tipData":[{"name":"设备总数","value":529},{"name":"企业总数","value":1}]},{"name":"遵义市","value":10,"tipData":[{"name":"设备总数","value":511},{"name":"企业总数","value":1}]},{"name":"哈尔滨市","value":10,"tipData":[{"name":"设备总数","value":511},{"name":"企业总数","value":1}]},{"name":"自贡市","value":10,"tipData":[{"name":"设备总数","value":507},{"name":"企业总数","value":1}]},{"name":"龙岩市","value":10,"tipData":[{"name":"设备总数","value":500},{"name":"企业总数","value":1}]},{"name":"吴忠市","value":10,"tipData":[{"name":"设备总数","value":500},{"name":"企业总数","value":1}]},{"name":"枣庄市","value":10,"tipData":[{"name":"设备总数","value":488},{"name":"企业总数","value":1}]},{"name":"南昌市","value":10,"tipData":[{"name":"设备总数","value":466},{"name":"企业总数","value":1}]},{"name":"金华市","value":10,"tipData":[{"name":"设备总数","value":444},{"name":"企业总数","value":1}]},{"name":"聊城市","value":10,"tipData":[{"name":"设备总数","value":435},{"name":"企业总数","value":1}]},{"name":"宁波市","value":10,"tipData":[{"name":"设备总数","value":428},{"name":"企业总数","value":1}]},{"name":"芜湖市","value":10,"tipData":[{"name":"设备总数","value":421},{"name":"企业总数","value":1}]},{"name":"威海市","value":10,"tipData":[{"name":"设备总数","value":420},{"name":"企业总数","value":1}]},{"name":"漳州市","value":10,"tipData":[{"name":"设备总数","value":406},{"name":"企业总数","value":1}]},{"name":"呼和浩特市","value":10,"tipData":[{"name":"设备总数","value":405},{"name":"企业总数","value":1}]},{"name":"西安市","value":10,"tipData":[{"name":"设备总数","value":374},{"name":"企业总数","value":1}]},{"name":"唐山市","value":10,"tipData":[{"name":"设备总数","value":372},{"name":"企业总数","value":1}]},{"name":"德州市","value":10,"tipData":[{"name":"设备总数","value":365},{"name":"企业总数","value":1}]},{"name":"乌海市","value":10,"tipData":[{"name":"设备总数","value":350},{"name":"企业总数","value":1}]},{"name":"玉林市","value":10,"tipData":[{"name":"设备总数","value":347},{"name":"企业总数","value":1}]},{"name":"安顺市","value":10,"tipData":[{"name":"设备总数","value":324},{"name":"企业总数","value":1}]},{"name":"湖州市","value":10,"tipData":[{"name":"设备总数","value":306},{"name":"企业总数","value":1}]},{"name":"来宾市","value":10,"tipData":[{"name":"设备总数","value":300},{"name":"企业总数","value":1}]},{"name":"保定市","value":10,"tipData":[{"name":"设备总数","value":299},{"name":"企业总数","value":1}]},{"name":"萍乡市","value":10,"tipData":[{"name":"设备总数","value":277},{"name":"企业总数","value":1}]},{"name":"宝鸡市","value":10,"tipData":[{"name":"设备总数","value":273},{"name":"企业总数","value":1}]},{"name":"桂林市","value":10,"tipData":[{"name":"设备总数","value":271},{"name":"企业总数","value":1}]},{"name":"石家庄市","value":10,"tipData":[{"name":"设备总数","value":265},{"name":"企业总数","value":1}]},{"name":"六安市","value":10,"tipData":[{"name":"设备总数","value":261},{"name":"企业总数","value":1}]},{"name":"宿州市","value":10,"tipData":[{"name":"设备总数","value":253},{"name":"企业总数","value":1}]},{"name":"马鞍山市","value":10,"tipData":[{"name":"设备总数","value":251},{"name":"企业总数","value":1}]},{"name":"黄山市","value":10,"tipData":[{"name":"设备总数","value":248},{"name":"企业总数","value":1}]},{"name":"新余市","value":10,"tipData":[{"name":"设备总数","value":242},{"name":"企业总数","value":1}]},{"name":"亳州市","value":10,"tipData":[{"name":"设备总数","value":219},{"name":"企业总数","value":1}]},{"name":"阜阳市","value":10,"tipData":[{"name":"设备总数","value":200},{"name":"企业总数","value":1}]},{"name":"长治市","value":10,"tipData":[{"name":"设备总数","value":184},{"name":"企业总数","value":1}]},{"name":"毕节市","value":10,"tipData":[{"name":"设备总数","value":170},{"name":"企业总数","value":1}]},{"name":"鄂尔多斯市","value":10,"tipData":[{"name":"设备总数","value":165},{"name":"企业总数","value":1}]},{"name":"克拉玛依市","value":10,"tipData":[{"name":"设备总数","value":164},{"name":"企业总数","value":1}]},{"name":"自治区直辖县级行政区划","value":10,"tipData":[{"name":"设备总数","value":154},{"name":"企业总数","value":1}]},{"name":"贵港市","value":10,"tipData":[{"name":"设备总数","value":146},{"name":"企业总数","value":1}]},{"name":"包头市","value":10,"tipData":[{"name":"设备总数","value":143},{"name":"企业总数","value":1}]},{"name":"东营市","value":10,"tipData":[{"name":"设备总数","value":134},{"name":"企业总数","value":1}]},{"name":"赣州市","value":10,"tipData":[{"name":"设备总数","value":134},{"name":"企业总数","value":1}]},{"name":"榆林市","value":10,"tipData":[{"name":"设备总数","value":132},{"name":"企业总数","value":1}]},{"name":"咸宁市","value":10,"tipData":[{"name":"设备总数","value":123},{"name":"企业总数","value":1}]},{"name":"黄冈市","value":10,"tipData":[{"name":"设备总数","value":120},{"name":"企业总数","value":1}]},{"name":"营口市","value":10,"tipData":[{"name":"设备总数","value":120},{"name":"企业总数","value":1}]},{"name":"承德市","value":10,"tipData":[{"name":"设备总数","value":119},{"name":"企业总数","value":1}]},{"name":"乐山市","value":10,"tipData":[{"name":"设备总数","value":118},{"name":"企业总数","value":1}]},{"name":"随州市","value":10,"tipData":[{"name":"设备总数","value":118},{"name":"企业总数","value":1}]},{"name":"忻州市","value":10,"tipData":[{"name":"设备总数","value":109},{"name":"企业总数","value":1}]},{"name":"邵阳市","value":10,"tipData":[{"name":"设备总数","value":107},{"name":"企业总数","value":1}]},{"name":"晋中市","value":10,"tipData":[{"name":"设备总数","value":103},{"name":"企业总数","value":1}]},{"name":"龙海市","value":10,"tipData":[{"name":"设备总数","value":100},{"name":"企业总数","value":1}]},{"name":"曲靖市","value":10,"tipData":[{"name":"设备总数","value":99},{"name":"企业总数","value":1}]},{"name":"张家口市","value":10,"tipData":[{"name":"设备总数","value":97},{"name":"企业总数","value":1}]},{"name":"宜昌市","value":10,"tipData":[{"name":"设备总数","value":97},{"name":"企业总数","value":1}]},{"name":"上海市","value":10,"tipData":[{"name":"设备总数","value":94},{"name":"企业总数","value":1}]},{"name":"长春市","value":10,"tipData":[{"name":"设备总数","value":91},{"name":"企业总数","value":1}]},{"name":"衡水市","value":10,"tipData":[{"name":"设备总数","value":84},{"name":"企业总数","value":1}]},{"name":"河池市","value":10,"tipData":[{"name":"设备总数","value":80},{"name":"企业总数","value":1}]},{"name":"衢州市","value":10,"tipData":[{"name":"设备总数","value":76},{"name":"企业总数","value":1}]},{"name":"抚顺市","value":10,"tipData":[{"name":"设备总数","value":75},{"name":"企业总数","value":1}]},{"name":"松原市","value":10,"tipData":[{"name":"设备总数","value":73},{"name":"企业总数","value":1}]},{"name":"锦州市","value":10,"tipData":[{"name":"设备总数","value":68},{"name":"企业总数","value":1}]},{"name":"楚雄彝族自治州","value":10,"tipData":[{"name":"设备总数","value":66},{"name":"企业总数","value":1}]},{"name":"绵阳市","value":10,"tipData":[{"name":"设备总数","value":66},{"name":"企业总数","value":1}]},{"name":"阳泉市","value":10,"tipData":[{"name":"设备总数","value":65},{"name":"企业总数","value":1}]},{"name":"铜仁市","value":10,"tipData":[{"name":"设备总数","value":64},{"name":"企业总数","value":1}]},{"name":"绥化市","value":10,"tipData":[{"name":"设备总数","value":62},{"name":"企业总数","value":1}]},{"name":"六盘水市","value":10,"tipData":[{"name":"设备总数","value":61},{"name":"企业总数","value":1}]},{"name":"七台河市","value":10,"tipData":[{"name":"设备总数","value":54},{"name":"企业总数","value":1}]},{"name":"铁岭市","value":10,"tipData":[{"name":"设备总数","value":52},{"name":"企业总数","value":1}]},{"name":"莱芜市","value":10,"tipData":[{"name":"设备总数","value":51},{"name":"企业总数","value":1}]},{"name":"梧州市","value":10,"tipData":[{"name":"设备总数","value":50},{"name":"企业总数","value":1}]},{"name":"鸡西市","value":10,"tipData":[{"name":"设备总数","value":50},{"name":"企业总数","value":1}]},{"name":"黔东南苗族侗族自治州","value":10,"tipData":[{"name":"设备总数","value":46},{"name":"企业总数","value":1}]},{"name":"广元市","value":10,"tipData":[{"name":"设备总数","value":46},{"name":"企业总数","value":1}]},{"name":"黔西南布依族苗族自治州","value":10,"tipData":[{"name":"设备总数","value":44},{"name":"企业总数","value":1}]},{"name":"资阳市","value":10,"tipData":[{"name":"设备总数","value":43},{"name":"企业总数","value":1}]},{"name":"孝感市","value":10,"tipData":[{"name":"设备总数","value":42},{"name":"企业总数","value":1}]},{"name":"巴中市","value":10,"tipData":[{"name":"设备总数","value":40},{"name":"企业总数","value":1}]},{"name":"盘锦市","value":10,"tipData":[{"name":"设备总数","value":37},{"name":"企业总数","value":1}]},{"name":"佳木斯市","value":10,"tipData":[{"name":"设备总数","value":35},{"name":"企业总数","value":1}]},{"name":"丽水市","value":10,"tipData":[{"name":"设备总数","value":34},{"name":"企业总数","value":1}]},{"name":"日照市","value":10,"tipData":[{"name":"设备总数","value":34},{"name":"企业总数","value":1}]},{"name":"赤峰市","value":10,"tipData":[{"name":"设备总数","value":28},{"name":"企业总数","value":1}]},{"name":"伊春市","value":10,"tipData":[{"name":"设备总数","value":25},{"name":"企业总数","value":1}]},{"name":"济宁市","value":10,"tipData":[{"name":"设备总数","value":25},{"name":"企业总数","value":1}]},{"name":"黔南布依族苗族自治州","value":10,"tipData":[{"name":"设备总数","value":24},{"name":"企业总数","value":1}]},{"name":"县","value":10,"tipData":[{"name":"设备总数","value":22},{"name":"企业总数","value":1}]},{"name":"邢台市","value":10,"tipData":[{"name":"设备总数","value":22},{"name":"企业总数","value":1}]},{"name":"汉中市","value":10,"tipData":[{"name":"设备总数","value":21},{"name":"企业总数","value":1}]},{"name":"抚州市","value":10,"tipData":[{"name":"设备总数","value":21},{"name":"企业总数","value":1}]},{"name":"阿拉善盟","value":10,"tipData":[{"name":"设备总数","value":20},{"name":"企业总数","value":1}]},{"name":"荆门市","value":10,"tipData":[{"name":"设备总数","value":20},{"name":"企业总数","value":1}]},{"name":"哈密市","value":10,"tipData":[{"name":"设备总数","value":15},{"name":"企业总数","value":1}]},{"name":"晋城市","value":10,"tipData":[{"name":"设备总数","value":14},{"name":"企业总数","value":1}]},{"name":"娄底市","value":10,"tipData":[{"name":"设备总数","value":8},{"name":"企业总数","value":1}]},{"name":"平凉市","value":10,"tipData":[{"name":"设备总数","value":8},{"name":"企业总数","value":1}]},{"name":"淄博市","value":10,"tipData":[{"name":"设备总数","value":8},{"name":"企业总数","value":1}]},{"name":"九江市","value":10,"tipData":[{"name":"设备总数","value":6},{"name":"企业总数","value":1}]},{"name":"葫芦岛市","value":10,"tipData":[{"name":"设备总数","value":6},{"name":"企业总数","value":1}]},{"name":"淮南市","value":10,"tipData":[{"name":"设备总数","value":5},{"name":"企业总数","value":1}]},{"name":"襄阳市","value":10,"tipData":[{"name":"设备总数","value":4},{"name":"企业总数","value":1}]},{"name":"滁州市","value":10,"tipData":[{"name":"设备总数","value":4},{"name":"企业总数","value":1}]},{"name":"郴州市","value":10,"tipData":[{"name":"设备总数","value":3},{"name":"企业总数","value":1}]},{"name":"吐鲁番市","value":10,"tipData":[{"name":"设备总数","value":3},{"name":"企业总数","value":1}]},{"name":"吉安市","value":10,"tipData":[{"name":"设备总数","value":3},{"name":"企业总数","value":1}]},{"name":"凉山彝族自治州","value":10,"tipData":[{"name":"设备总数","value":3},{"name":"企业总数","value":1}]},{"name":"宜宾市","value":10,"tipData":[{"name":"设备总数","value":2},{"name":"企业总数","value":1}]},{"name":"拉萨市","value":10,"tipData":[{"name":"设备总数","value":2},{"name":"企业总数","value":1}]},{"name":"广安市","value":10,"tipData":[{"name":"设备总数","value":2},{"name":"企业总数","value":1}]},{"name":"昆明市","value":10,"tipData":[{"name":"设备总数","value":2},{"name":"企业总数","value":1}]},{"name":"黄石市","value":10,"tipData":[{"name":"设备总数","value":1},{"name":"企业总数","value":1}]},{"name":"保山市","value":10,"tipData":[{"name":"设备总数","value":1},{"name":"企业总数","value":1}]},{"name":"荆州市","value":10,"tipData":[{"name":"设备总数","value":1},{"name":"企业总数","value":1}]},{"name":"怀化市","value":10,"tipData":[{"name":"设备总数","value":1},{"name":"企业总数","value":1}]},{"name":"博尔塔拉蒙古自治州","value":10,"tipData":[{"name":"设备总数","value":1},{"name":"企业总数","value":1}]},{"name":"恩施土家族苗族自治州","value":10,"tipData":[{"name":"设备总数","value":1},{"name":"企业总数","value":1}]},{"name":"鄂州市","value":10,"tipData":[{"name":"设备总数","value":1},{"name":"企业总数","value":1}]},{"name":"喀什地区","value":10,"tipData":[{"name":"设备总数","value":1},{"name":"企业总数","value":1}]},{"name":"乌兰察布市","value":10,"tipData":[{"name":"设备总数","value":1},{"name":"企业总数","value":1}]},{"name":"石景山区","value":10,"tipData":[{"name":"设备总数","value":16},{"name":"企业总数","value":1}]},{"name":"海淀区","value":10,"tipData":[{"name":"设备总数","value":2},{"name":"企业总数","value":1}]},{"name":"朝阳区","value":10,"tipData":[{"name":"设备总数","value":1},{"name":"企业总数","value":1}]},{"name":"黄浦区","value":10,"tipData":[{"name":"设备总数","value":28342},{"name":"企业总数","value":1}]},{"name":"嘉定区","value":10,"tipData":[{"name":"设备总数","value":25},{"name":"企业总数","value":1}]},{"name":"浦东新区","value":10,"tipData":[{"name":"设备总数","value":35},{"name":"企业总数","value":1}]},{"name":"和平区","value":10,"tipData":[{"name":"设备总数","value":6},{"name":"企业总数","value":1}]},{"name":"河东区","value":10,"tipData":[{"name":"设备总数","value":3},{"name":"企业总数","value":1}]},{"name":"河西区","value":10,"tipData":[{"name":"设备总数","value":406},{"name":"企业总数","value":1}]},{"name":"南开区","value":10,"tipData":[{"name":"设备总数","value":385},{"name":"企业总数","value":1}]},{"name":"东丽区","value":10,"tipData":[{"name":"设备总数","value":19236},{"name":"企业总数","value":1}]},{"name":"西青区","value":10,"tipData":[{"name":"设备总数","value":243},{"name":"企业总数","value":1}]},{"name":"武清区","value":10,"tipData":[{"name":"设备总数","value":9},{"name":"企业总数","value":1}]},{"name":"宝坻区","value":10,"tipData":[{"name":"设备总数","value":2},{"name":"企业总数","value":1}]},{"name":"静海区","value":10,"tipData":[{"name":"设备总数","value":12861},{"name":"企业总数","value":1}]},{"name":"万州区","value":10,"tipData":[{"name":"设备总数","value":21},{"name":"企业总数","value":1}]},{"name":"渝中区","value":10,"tipData":[{"name":"设备总数","value":2},{"name":"企业总数","value":1}]},{"name":"江北区","value":10,"tipData":[{"name":"设备总数","value":503},{"name":"企业总数","value":1}]},{"name":"南岸区","value":10,"tipData":[{"name":"设备总数","value":4},{"name":"企业总数","value":1}]},{"name":"巴南区","value":10,"tipData":[{"name":"设备总数","value":4},{"name":"企业总数","value":1}]},{"name":"黔江区","value":10,"tipData":[{"name":"设备总数","value":13112},{"name":"企业总数","value":1}]},{"name":"开州区","value":10,"tipData":[{"name":"设备总数","value":5},{"name":"企业总数","value":1}]}]'

let qiye = [
  {"city":"包头市", value:"6"},
  {"city":"宝鸡市", value:"1"},
  {"city":"保定市", value:"1"},
  {"city":"东城区", value:"28"},
  {"city":"常州市", value:"352"},
  {"city":"成都市", value:"43"},
  {"city":"赤峰市", value:"1"},
  {"city":"德阳市", value:"8"},
  {"city":"东莞市", value:"4"},
  {"city":"佛山市", value:"21"},
  {"city":"赣州市", value:"2"},
  {"city":"广汉市", value:"2"},
  {"city":"广州市", value:"4"},
  {"city":"贵阳市", value:"9"},
  {"city":"杭州市", value:"4"},
  {"city":"济南市", value:"1"},
  {"city":"济宁市", value:"1"},
  {"city":"昆明市", value:"1"},
  {"city":"兰州市", value:"3"},
  {"city":"廊坊市", value:"2"},
  {"city":"洛阳市", value:"1"},
  {"city":"眉山市", value:"1"},
  {"city":"南昌市", value:"2"},
  {"city":"南京市", value:"14"},
  {"city":"宁波市", value:"1"},
  {"city":"盘锦市", value:"1"},
  {"city":"衢州市", value:"1"},
  {"city":"日照市", value:"1"},
  {"city":"厦门市", value:"4"},
  {"city":"浦东新区", value:"2"},
  {"city":"深圳市", value:"6"},
  {"city":"沈阳市", value:"10"},
  // {"city":"四川省", value:"11"},
  {"city":"苏州市", value:"2"},
  {"city":"随州市", value:"1"},
  {"city":"河东区", value:"8"},
  {"city":"铁岭市", value:"1"},
  {"city":"无锡市", value:"1"},
  {"city":"武汉市", value:"8"},
  {"city":"西安市", value:"3"},
  {"city":"孝感市", value:"3"},
  {"city":"雅安市", value:"1"},
  {"city":"烟台市", value:"1"},
  {"city":"阳江市", value:"1"},
  {"city":"宜宾市", value:"1"},
  {"city":"榆林市", value:"1"},
  {"city":"玉林市", value:"1"},
  {"city":"长沙市", value:"1"},
  {"city":"长治市", value:"1"},
  {"city":"肇庆市", value:"1"},
  {"city":"镇江市", value:"1"},
  {"city":"中山市", value:"2"},
  {"city":"北碚区", value:"8"},
  {"city":"珠海市", value:"1"},
  {"city":"资阳市", value:"1"},
  {"city":"自贡市", value:"1"},
]

let provinceQiye = [
  {"name":"江苏","value":"490"},
  {"name":"四川","value":"87"},
  {"name":"北京","value":"46"},
  {"name":"广东","value":"31"},
  {"name":"辽宁","value":"19"},
  {"name":"贵州","value":"18"},
  {"name":"湖北","value":"16"},
  {"name":"河北","value":"15"},
  {"name":"天津","value":"14"},
  {"name":"内蒙古","value":"11"},
  {"name":"陕西","value":"11"},
  {"name":"浙江","value":"10"},
  {"name":"重庆","value":"10"},
  {"name":"江西","value":"9"},
  {"name":"湖南","value":"8"},
  {"name":"山东","value":"7"},
  {"name":"黑龙江","value":"5"},
  {"name":"上海","value":"5"},
  {"name":"福建","value":"5"},
  {"name":"山西","value":"5"},
  {"name":"河南","value":"5"},
  {"name":"云南","value":"4"},
  {"name":"甘肃","value":"4"},
  {"name":"吉林","value":"3"},
  {"name":"广西","value":"3"},
  {"name":"安徽","value":"2"},
  {"name":"新疆","value":"2"},
  // {"name":"(空白)","value":"1"},
  {"name":"宁夏","value":"1"},
  {"name":"西藏","value":"1"}
]

let cityQiye = [
  {"name":"常州市","value":"446"},
  {"name":"成都市","value":"63"},
  {"name":"北京市辖区","value":"46"},
  {"name":"无锡市","value":"26"},
  {"name":"佛山市","value":"15"},
  {"name":"德阳市","value":"15"},
  {"name":"天津市辖区","value":"14"},
  {"name":"镇江市","value":"13"},
  {"name":"沈阳市","value":"12"},
  {"name":"重庆市辖区","value":"10"},
  {"name":"贵阳市","value":"10"},
  {"name":"苏州市","value":"9"},
  {"name":"深圳市","value":"8"},
  {"name":"南京市","value":"8"},
  {"name":"西安市","value":"7"},
  {"name":"廊坊市","value":"6"},
  {"name":"广州市","value":"6"},
  {"name":"孝感市","value":"5"},
  {"name":"赣州市","value":"5"},
  {"name":"遵义市","value":"5"},
  {"name":"上海市辖区","value":"5"},
  {"name":"厦门市","value":"5"},
  {"name":"兰州市","value":"4"},
  {"name":"益阳市","value":"4"},
  {"name":"呼和浩特市","value":"4"},
  {"name":"宁波市","value":"4"},
  {"name":"张家口市","value":"4"},
  {"name":"十堰市","value":"4"},
  {"name":"杭州市","value":"4"},
  {"name":"盐城市","value":"4"},
  {"name":"扬州市","value":"4"},
  {"name":"南昌市","value":"4"},
  {"name":"武汉市","value":"3"},
  {"name":"肇庆市","value":"3"},
  {"name":"大同市","value":"3"},
  {"name":"包头市","value":"3"},
  {"name":"石家庄市","value":"3"},
  {"name":"宝鸡市","value":"3"},
  {"name":"徐州市","value":"3"},
  {"name":"衡水市","value":"3"},
  {"name":"营口市","value":"3"},
  {"name":"济南市","value":"3"},
  {"name":"安顺市","value":"3"},
  {"name":"九江市","value":"3"},
  {"name":"随州市","value":"3"},
  {"name":"毕节市","value":"3"},
  {"name":"新乡市","value":"3"},
  {"name":"洛阳市","value":"3"},
  {"name":"烟台市","value":"3"},
  {"name":"眉山市","value":"3"},
  {"name":"阳江市","value":"3"},
  {"name":"绵阳市","value":"3"},
  {"name":"东莞市","value":"3"},
  {"name":"秦皇岛市","value":"3"},
  {"name":"鄂尔多斯市","value":"3"},
  {"name":"商丘市","value":"3"},
  {"name":"潮州市","value":"3"},
  {"name":"哈尔滨市","value":"2"},
  {"name":"哈密市","value":"2"},
  {"name":"云浮市","value":"2"},
  {"name":"抚顺市","value":"2"},
  {"name":"信阳市","value":"2"},
  {"name":"南通市","value":"2"},
  {"name":"德州市","value":"2"},
  {"name":"南阳市","value":"2"},
  {"name":"长治市","value":"2"},
  {"name":"盘锦市","value":"2"},
  {"name":"忻州市","value":"2"},
  {"name":"淮安市","value":"2"},
  {"name":"宿州市","value":"2"},
  {"name":"清远市","value":"2"},
  {"name":"聊城市","value":"2"},
  {"name":"日照市","value":"2"},
  {"name":"榆林市","value":"2"},
  {"name":"三门峡市","value":"2"},
  {"name":"长春市","value":"2"},
  {"name":"汕头市","value":"2"},
  {"name":"郑州市","value":"2"},
  {"name":"惠州市","value":"2"},
  {"name":"珠海市","value":"2"},
  {"name":"保定市","value":"2"},
  {"name":"克拉玛依市","value":"2"},
  {"name":"驻马店市","value":"2"},
  {"name":"宿迁市","value":"2"},
  {"name":"安阳市","value":"2"},
  {"name":"莱芜市","value":"2"},
  {"name":"焦作市","value":"2"},
  {"name":"凉山彝族自治州","value":"2"},
  {"name":"绥化市","value":"2"},
  {"name":"宜昌市","value":"2"},
  {"name":"锦州市","value":"2"},
  {"name":"临沂市","value":"2"},
  {"name":"太原市","value":"2"},
  {"name":"玉林市","value":"2"},
  {"name":"泰州市","value":"2"},
  {"name":"六盘水市","value":"2"},
  {"name":"赤峰市","value":"2"},
  {"name":"长沙市","value":"2"},
  {"name":"铁岭市","value":"2"},
  {"name":"娄底市","value":"2"},
  {"name":"威海市","value":"2"},
  {"name":"中山市","value":"2"},
  {"name":"温州市","value":"2"},
  {"name":"周口市","value":"2"},
  {"name":"桂林市","value":"2"},
  {"name":"鹤壁市","value":"2"},
  {"name":"大连市","value":"2"},
  {"name":"青岛市","value":"2"},
  {"name":"咸宁市","value":"1"},
  {"name":"广元市","value":"1"},
  {"name":"鞍山市","value":"1"},
  // {"name":"(空白)","value":"1"},
  {"name":"鄂州市","value":"1"},
  {"name":"亳州市","value":"1"},
  {"name":"汉中市","value":"1"},
  {"name":"南平市","value":"1"},
  {"name":"鹰潭市","value":"1"},
  {"name":"贵港市","value":"1"},
  {"name":"葫芦岛市","value":"1"},
  {"name":"淮南市","value":"1"},
  {"name":"吴忠市","value":"1"},
  {"name":"博尔塔拉蒙古自治州","value":"1"},
  {"name":"邯郸市","value":"1"},
  {"name":"黄冈市","value":"1"},
  {"name":"来宾市","value":"1"},
  {"name":"平顶山市","value":"1"},
  {"name":"宜宾市","value":"1"},
  {"name":"平凉市","value":"1"},
  {"name":"临汾市","value":"1"},
  {"name":"萍乡市","value":"1"},
  {"name":"巴中市","value":"1"},
  {"name":"濮阳市","value":"1"},
  {"name":"梅州市","value":"1"},
  {"name":"七台河市","value":"1"},
  {"name":"滁州市","value":"1"},
  {"name":"黔东南苗族侗族自治州","value":"1"},
  {"name":"荆州市","value":"1"},
  {"name":"黔南布依族苗族自治州","value":"1"},
  {"name":"湘潭市","value":"1"},
  {"name":"黔西南布依族苗族自治州","value":"1"},
  {"name":"开封市","value":"1"},
  {"name":"黄山市","value":"1"},
  {"name":"昆明市","value":"1"},
  {"name":"恩施土家族苗族自治州","value":"1"},
  {"name":"保山市","value":"1"},
  {"name":"黄石市","value":"1"},
  {"name":"阳泉市","value":"1"},
  {"name":"衢州市","value":"1"},
  {"name":"丽水市","value":"1"},
  {"name":"曲靖市","value":"1"},
  {"name":"河池市","value":"1"},
  {"name":"抚州市","value":"1"},
  {"name":"枣庄市","value":"1"},
  {"name":"鸡西市","value":"1"},
  {"name":"柳州市","value":"1"},
  {"name":"三明市","value":"1"},
  {"name":"东营市","value":"1"},
  {"name":"沧州市","value":"1"},
  {"name":"茂名市","value":"1"},
  {"name":"吉安市","value":"1"},
  {"name":"淄博市","value":"1"},
  {"name":"汕尾市","value":"1"},
  {"name":"乌鲁木齐市","value":"1"},
  {"name":"吉林市","value":"1"},
  {"name":"芜湖市","value":"1"},
  {"name":"阜阳市","value":"1"},
  {"name":"梧州市","value":"1"},
  {"name":"韶关市","value":"1"},
  {"name":"楚雄彝族自治州","value":"1"},
  {"name":"邵阳市","value":"1"},
  {"name":"县","value":"1"},
  {"name":"绍兴市","value":"1"},
  {"name":"襄阳市","value":"1"},
  {"name":"济宁市","value":"1"},
  {"name":"喀什地区","value":"1"},
  {"name":"郴州市","value":"1"},
  {"name":"新余市","value":"1"},
  {"name":"省直辖县级行政区划","value":"1"},
  {"name":"邢台市","value":"1"},
  {"name":"佳木斯市","value":"1"},
  {"name":"拉萨市","value":"1"},
  {"name":"嘉兴市","value":"1"},
  {"name":"宣城市","value":"1"},
  {"name":"朔州市","value":"1"},
  {"name":"合肥市","value":"1"},
  {"name":"松原市","value":"1"},
  {"name":"滨州市","value":"1"},
  {"name":"承德市","value":"1"},
  {"name":"伊春市","value":"1"},
  {"name":"江门市","value":"1"},
  {"name":"乐山市","value":"1"},
  {"name":"福州市","value":"1"},
  {"name":"银川市","value":"1"},
  {"name":"台州市","value":"1"},
  {"name":"连云港市","value":"1"},
  {"name":"揭阳市","value":"1"},
  {"name":"河源市","value":"1"},
  {"name":"泰安市","value":"1"},
  {"name":"运城市","value":"1"},
  {"name":"金华市","value":"1"},
  {"name":"湛江市","value":"1"},
  {"name":"唐山市","value":"1"},
  {"name":"漳州市","value":"1"},
  {"name":"广安市","value":"1"},
  {"name":"六安市","value":"1"},
  {"name":"晋城市","value":"1"},
  {"name":"龙岩市","value":"1"},
  {"name":"铜仁市","value":"1"},
  {"name":"阿拉善盟","value":"1"},
  {"name":"吐鲁番市","value":"1"},
  {"name":"马鞍山市","value":"1"},
  {"name":"晋中市","value":"1"},
  {"name":"湖州市","value":"1"},
  {"name":"潍坊市","value":"1"},
  {"name":"资阳市","value":"1"},
  {"name":"荆门市","value":"1"},
  {"name":"自贡市","value":"1"},
  {"name":"乌海市","value":"1"},
  {"name":"怀化市","value":"1"},
  {"name":"乌兰察布市","value":"1"},
]

const total_data = JSON.parse(cityData);

// qiye.forEach((val, i) => {
//   total_data.forEach((v, k) => {
//     if (val.city === v.name) {
//       v.tipData[1].value = val.value
//     }
//   })
// })

provinceQiye.forEach((val, i) => {
  total_data.forEach((v, k) => {
    if (val.name === v.name) {
      v.tipData[1].value = Number(val.value)
    }
  })
})

cityQiye.forEach((val, i) => {
  total_data.forEach((v, k) => {
    if (val.name === v.name) {
      v.tipData[1].value = Number(val.value)
    }
  })
})

export default total_data;
